/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nyFormulaire;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nyClasses.client;
import nyClasses.produit;
import nyGestionBd.gest_client;
import nyGestionBd.gest_produit;

/**
 *
 * @author TSIAHY DONILLY
 */
public class crude_produit extends javax.swing.JInternalFrame {

    /**
     * Creates new form crude_produit
     */
    public crude_produit() {
        initComponents();
        chargerListe();

    }

    public void actualiser() {
        txt_carte.setText("");
        txt_cpu.setText("");
        nbr_dur.setText("");
        nbr_quantite.setText("");
        nbr_ram.setText("");
        nbr_vidy.setText("");
        txt_carte.setText("");
        txt_marque.setText("");
    }

    public void chargerListe() {
        String titre[] = {"reference_produit", "marque", "ram", "stockage", "carte_graphique", "cpu", "vidy", "quantite"};
        Object save[][] = new Object[1][1];
        try {
            gest_produit gp = new gest_produit();
            int nbr = gp.countSave();
            save = new Object[nbr][titre.length];

            ResultSet res = gp.getPRODUIT();

            int i = 0;
            while (res.next()) {
                save[i][0] = (Object) res.getString("reference_produit");
                save[i][1] = (Object) res.getString("marque");
                save[i][2] = (Object) res.getString("ram");
                save[i][3] = (Object) res.getString("stockage");
                save[i][4] = (Object) res.getString("carte_graphique");
                save[i][5] = (Object) res.getString("cpu");
                save[i][6] = (Object) res.getString("vidy");
                save[i][7] = (Object) res.getString("quantite");

                i++;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        tableau.setModel(new DefaultTableModel(save, titre));
        jScrollPane1.setViewportView(tableau);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_reference = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nbr_ram = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nbr_dur = new javax.swing.JTextField();
        txt_carte = new javax.swing.JTextField();
        nbr_quantite = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        txt_recherche = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nbr_vidy = new javax.swing.JTextField();
        txt_cpu = new javax.swing.JTextField();
        txt_marque = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1059, 656));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Reference_produit");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));
        jPanel1.add(txt_reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 223, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ram");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 60, -1));
        jPanel1.add(nbr_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 223, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marque");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Carte graphique");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("vidy");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("cpu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 60, -1));
        jPanel1.add(nbr_dur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, -1));
        jPanel1.add(txt_carte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 220, -1));
        jPanel1.add(nbr_quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 220, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/delete_16px.png"))); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, 30));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/add_16px.png"))); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 100, 30));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, 30));

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "null", "Title 8"
            }
        ));
        tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableau);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 540, 270));
        jPanel1.add(txt_recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 160, 30));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/search_24px.png"))); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/laptop_48px.png"))); // NOI18N
        jLabel7.setText("            PRODUIT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 300, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantite");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dur");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 90, -1));
        jPanel1.add(nbr_vidy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 220, -1));
        jPanel1.add(txt_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 220, -1));

        txt_marque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marqueActionPerformed(evt);
            }
        });
        jPanel1.add(txt_marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String reference = txt_reference.getText();
        String marque = txt_marque.getText();
        String ram = nbr_ram.getText();
        String dur = nbr_dur.getText();
        String carte = txt_carte.getText();
        String cpu = txt_cpu.getText();
        String vidy = nbr_vidy.getText();
        String quantite = nbr_quantite.getText();
        if (reference.equals("") || ram.equals("") || dur.equals("") || marque.equals("") || carte.equals("") || cpu.equals("") || vidy.equals("") || quantite.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez remplir tous le champ");

        } else {
            try {
                gest_produit gp = new gest_produit();
                ResultSet res = gp.getPRODUIT();
                boolean misy = false;
                while (res.next()) {
                    String vreference = res.getString("reference_produit");
                    if (vreference.equals(reference)) {
                        misy = true;
                        break;
                    }
                }
                if (misy) {
                    JOptionPane.showMessageDialog(null, "produit efa misy ao io apidirinao io!!");
                } else {
                    int parsevidy = Integer.parseInt(vidy);
                    int parsequantite = Integer.parseInt(quantite);
                    produit produit1 = new produit(reference, marque, ram, dur, carte, cpu, parsevidy, parsequantite);
                    gp.insert(produit1);
                    JOptionPane.showMessageDialog(null, "tafiditraaaaa!!");
                    chargerListe();
                    actualiser();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauMouseClicked
        // TODO add your handling code here:

        int nbrow = tableau.getSelectedRow();
        txt_reference.setText(String.valueOf(tableau.getValueAt(nbrow, 0)));
        txt_marque.setText(String.valueOf(tableau.getValueAt(nbrow, 1)));

        nbr_ram.setText(String.valueOf(tableau.getValueAt(nbrow, 2)));
        nbr_dur.setText(String.valueOf(tableau.getValueAt(nbrow, 3)));
        txt_carte.setText(String.valueOf(tableau.getValueAt(nbrow, 4)));
        txt_cpu.setText(String.valueOf(tableau.getValueAt(nbrow, 5)));
        nbr_vidy.setText(String.valueOf(tableau.getValueAt(nbrow, 6)));
        nbr_quantite.setText(String.valueOf(tableau.getValueAt(nbrow, 7)));

    }//GEN-LAST:event_tableauMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String txt_condi = txt_reference.getText();

        if (txt_condi.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez selectioner l'element supprimer");
        } else {
            int p = JOptionPane.showConfirmDialog(null, "do you supprimer", "delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                try {

                    gest_produit gp = new gest_produit();
                    gp.delete(txt_condi);
                    JOptionPane.showMessageDialog(null, "suppresion reusii!!");
                    chargerListe();
                    actualiser();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String reference = txt_reference.getText();

        String marque = txt_marque.getText();
        String ram = nbr_ram.getText();

        String stockage = nbr_dur.getText();
        String carte = txt_carte.getText();
        String cpu = txt_cpu.getText();
        String prix = nbr_vidy.getText();
        String quantite = nbr_quantite.getText();

        if (reference.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez selection l'element que vous voulez modifier");
        } else {
            try {
                int paresprix = Integer.parseInt(prix);
                int paresquantite = Integer.parseInt(quantite);
                produit prod = new produit(reference, marque, ram, stockage, carte, cpu, paresprix, paresquantite);
                gest_produit gp = new gest_produit();
                gp.update(reference, prod);
                JOptionPane.showMessageDialog(null, "modification reussi!!");
                chargerListe();
                actualiser();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ref = txt_recherche.getText();

        String titre[] = {"reference_produit", "marque", "ram", "stockage", "carte_graphique", "cpu", "prix", "quantite"};
        Object save[][] = new Object[1][1];

        try {
            gest_produit gp = new gest_produit();

            int nbr = gp.countSave();
            save = new Object[nbr][titre.length];

            ResultSet res = gp.getByRef(ref);
            int i = 0;
            while (res.next()) {
                save[i][0] = (Object) res.getString("reference_produit");
                save[i][1] = (Object) res.getString("marque");
                save[i][2] = (Object) res.getString("ram");
                save[i][3] = (Object) res.getString("stockage");
                save[i][4] = (Object) res.getString("carte_graphique");
                save[i][5] = (Object) res.getString("cpu");
                save[i][6] = (Object) res.getString("vidy");
                save[i][7] = (Object) res.getString("quantite");

                i++;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        tableau.setModel(new DefaultTableModel(save, titre));
        jScrollPane1.setViewportView(tableau);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_marqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nbr_dur;
    private javax.swing.JTextField nbr_quantite;
    private javax.swing.JTextField nbr_ram;
    private javax.swing.JTextField nbr_vidy;
    private javax.swing.JTable tableau;
    private javax.swing.JTextField txt_carte;
    private javax.swing.JTextField txt_cpu;
    private javax.swing.JTextField txt_marque;
    private javax.swing.JTextField txt_recherche;
    private javax.swing.JTextField txt_reference;
    // End of variables declaration//GEN-END:variables
}
