/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nyFormulaire;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import nyClasses.achat;
import nyClasses.client;
import nyClasses.commande;
import nyGestionBd.gest_achat;
import nyGestionBd.gest_client;
import nyGestionBd.gest_commande;
import nyGestionBd.gest_produit;

/**
 *
 * @author TSIAHY DONILLY
 */
public class crude_achat extends javax.swing.JInternalFrame {

    /**
     * Creates new form crude_achet
     */
    public crude_achat() {
        initComponents();
        chargerListe();
        actualiser();
    }
    public void actualiser(){
        txt_reference.setText("");
        nbr_id.setText("");
        date.setDate(null);
        nbr_quantite1.setText("");
        nbr_prix.setText("");
    }
  public void chargerListe() {
        String titre[] = {"reference_produit", "id_client", "date", "quantite" ,"prix"};
        Object save[][] = new Object[1][1];
        try {
            gest_achat ga=new gest_achat();
            int nbr = ga.countSave();
            save = new Object[nbr][titre.length];

            ResultSet res = ga.getACHAT();

            int i = 0;
            while (res.next()) {
                save[i][0] = (Object) res.getString("reference_produit");
                save[i][1] = (Object) res.getString("id_client");
                save[i][2] = (Object) res.getString("date");
                save[i][3] = (Object) res.getString("quantite");
                save[i][4] = (Object) res.getString("prix");
                

                i++;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        tableau.setModel(new DefaultTableModel(save, titre));
        jScrollPane1.setViewportView(tableau);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nbr_id = new javax.swing.JTextField();
        txt_reference = new javax.swing.JTextField();
        nbr_prix = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        txt_rech = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        nbr_quantite1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1059, 656));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Refer_produit");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 228, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id_client");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 270, 56, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date_achat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Prix");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        jPanel1.add(nbr_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 183, -1));
        jPanel1.add(txt_reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 228, 183, -1));
        jPanel1.add(nbr_prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 183, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/buy_16px.png"))); // NOI18N
        jButton1.setText("ACHAT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 422, -1, 31));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 422, -1, 31));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/delete_16px.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 422, -1, 31));

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableau);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 228, -1, 287));
        jPanel1.add(txt_rech, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 172, 190, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/search_24px.png"))); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 172, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/buy_80px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 183, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantite");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 347, -1, -1));
        jPanel1.add(nbr_quantite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 344, 183, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
                String txt_condi = txt_reference.getText();

        if (txt_condi.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez selectioner l'element supprimer");
        } else {
            int p = JOptionPane.showConfirmDialog(null, "do you supprimer", "delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                try {

                    gest_achat ga=new gest_achat();
                    ga.delete(txt_condi);
                    JOptionPane.showMessageDialog(null, "suppresion reusii!!");
                    chargerListe();
                    actualiser();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauMouseClicked
        // TODO add your handling code here
        int nbrrow=tableau.getSelectedRow();
         txt_reference.setText(String.valueOf(tableau.getValueAt(nbrrow, 0)));
        nbr_id.setText(String.valueOf(tableau.getValueAt(nbrrow, 1)));
        try {
        
            SimpleDateFormat format =new SimpleDateFormat("yyyy-mm-dd");
            Date daty=format.parse(String.valueOf(tableau.getValueAt(nbrrow, 2)));
            date.setDate(daty);
            
        } catch (Exception e) {
            e.printStackTrace();
        nbr_quantite1.setText(String.valueOf(tableau.getValueAt(nbrrow, 3)));
        nbr_prix.setText(String.valueOf(tableau.getValueAt(nbrrow, 4)));
        }
       
    }//GEN-LAST:event_tableauMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String reference = txt_reference.getText();
        /* try {
            gest_achat ga=new gest_achat();
            ResultSet res=ga.getPrixProd(reference);
            while(res.next()){
                int pr=res.getInt("vidy");
                 System.out.println(pr);
                 String aa=String.valueOf(pr);
                 nbr_prix.setText(aa);            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        */
        String id_client = nbr_id.getText();
        String daty = ((JTextField) date.getDateEditor().getUiComponent()).getText();
        String quantite = nbr_prix.getText();
        String prix=nbr_prix.getText();
        

        if (reference.equals("") || id_client.equals("") || daty.equals("") || quantite.equals("")|| prix.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez remplir tous le champ");

        } else {
            try {
                gest_produit gp = new gest_produit();
                gest_client gcli = new gest_client();
                gest_achat ga=new gest_achat();
                int id = Integer.parseInt(id_client);
                int pri = Integer.parseInt(prix);
                int quanti=Integer.parseInt(quantite);
                achat achat1=new achat(reference, id, daty, quanti, pri);
                
                boolean clientExiste = false;
                boolean produitExiste = false;
                ResultSet res = gp.getPRODUIT();
                ResultSet resCli = gcli.getALLCLI();
                
                while (res.next()) {
                    String prod = res.getString("reference_produit");
                    if (prod.equals(reference)) {

                        produitExiste = true;
                        break;
                    }
                }
                while (resCli.next()) {
                    String idcli = resCli.getString("id_client");
                    if (idcli.equals(id_client)) {
                        clientExiste = true;

                        break;
                    }
                }
                while (res.next() || resCli.next()) {

                }
                if (!produitExiste) {
                    JOptionPane.showMessageDialog(null, "c'est produit ne pas encore enregistrer");
                } else if (!clientExiste) {
                    JOptionPane.showMessageDialog(null, "ce client n'existe pas,veullez le verifier");
                } else {

                    ga.insert(achat1);
                    JOptionPane.showMessageDialog(null, "ajout reussi");
                    chargerListe();
                    actualiser();

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String nume=txt_rech.getText();
        
        String titre[] = {"reference_produit", "id_client", "date", "quantite", "prix"};
        Object save[][] = new Object[1][1];
        
        try {
            gest_achat ga=new gest_achat();
                 
            int nbr = ga.countSave();
            save = new Object[nbr][titre.length];

            ResultSet res=ga.getByRef(nume);
            int i=0;
            while(res.next()){
                save[i][0] = (Object) res.getString("reference_produit");
                save[i][1] = (Object) res.getString("id_client");
                save[i][2] = (Object) res.getString("date");
                save[i][3] = (Object) res.getString("quantite");
                save[i][4] = (Object) res.getString("vidy");

                i++;
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        tableau.setModel(new DefaultTableModel(save, titre));
        jScrollPane1.setViewportView(tableau);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nbr_id;
    private javax.swing.JTextField nbr_prix;
    private javax.swing.JTextField nbr_quantite1;
    private javax.swing.JTable tableau;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_reference;
    // End of variables declaration//GEN-END:variables
}
