/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nyFormulaire;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import nyClasses.commande;
import nyClasses.produit;
import nyGestionBd.gest_achat;
import nyGestionBd.gest_client;
import nyGestionBd.gest_commande;
import nyGestionBd.gest_produit;

/**
 *
 * @author TSIAHY DONILLY
 */
public class crude_commande extends javax.swing.JInternalFrame {

    /**
     * Creates new form crude_commande
     */
    public crude_commande() {
        initComponents();
        chargerListe();
        actualiser();
    }

    public void actualiser() {
        txt_reference.setText("");
        date_commande.setDate(null);
        nbr_id_client.setText("");
        nbr_quantite.setText("");
    }

    public void chargerListe() {
        String titre[] = {"reference_produit", "id_client", "date", "quantite"};
        Object save[][] = new Object[1][1];
        try {
            gest_commande gcom = new gest_commande();
            int nbr = gcom.countSave();
            save = new Object[nbr][titre.length];

            ResultSet res = gcom.getCOMMANDE();

            int i = 0;
            while (res.next()) {
                save[i][0] = (Object) res.getString("reference_produit");
                save[i][1] = (Object) res.getString("id_client");
                save[i][2] = (Object) res.getString("date");
                save[i][3] = (Object) res.getString("quantite");

                i++;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        tableau.setModel(new DefaultTableModel(save, titre));
        jScrollPane1.setViewportView(tableau);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nbr_id_client = new javax.swing.JTextField();
        nbr_quantite = new javax.swing.JTextField();
        date_commande = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        txt_rech = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_reference = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1059, 656));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel3.setText("Id_client");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel4.setText("Quantite");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 80, -1));
        jPanel1.add(nbr_id_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 191, -1));
        jPanel1.add(nbr_quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 191, -1));

        date_commande.setDateFormatString("yyyy-mm-dd");
        jPanel1.add(date_commande, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 191, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/add_16px.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 31));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/delete_16px.png"))); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, 31));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 82, 31));

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableau);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, 310));
        jPanel1.add(txt_rech, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 190, 28));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/search_24px.png"))); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 130, 28));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setText("COMMANDE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 274, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel5.setText("Date_commande");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel6.setText("Reference_produit ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        jPanel1.add(txt_reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 191, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String reference = txt_reference.getText();
        String id_client = nbr_id_client.getText();
        String date = ((JTextField) date_commande.getDateEditor().getUiComponent()).getText();
        String quantite = nbr_quantite.getText();

        if (reference.equals("") || id_client.equals("") || date.equals("") || quantite.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez remplir tous le champ");

        } else {
            try {
                gest_produit gp = new gest_produit();
                gest_client gcli = new gest_client();
                gest_commande gc = new gest_commande();
                int id = Integer.parseInt(id_client);
                int prix = Integer.parseInt(quantite);
                commande commande1 = new commande(reference, id, date, prix);
                boolean clientExiste = false;
                boolean produitExiste = false;
                ResultSet res = gp.getPRODUIT();
                ResultSet resCli = gcli.getALLCLI();
                ResultSet gcom = gc.getCOMMANDE();
                while (res.next()) {
                    String prod = res.getString("reference_produit");
                    if (prod.equals(reference)) {

                        produitExiste = true;
                        break;
                    }
                }
                while (resCli.next()) {
                    String idcli = resCli.getString("id_client");
                    if (idcli.equals(id_client)) {
                        clientExiste = true;

                        break;
                    }
                }
                while (res.next() || resCli.next()) {

                }
                if (!produitExiste) {
                    JOptionPane.showMessageDialog(null, "c'est produit ne pas encore enregistrer");
                } else if (!clientExiste) {
                    JOptionPane.showMessageDialog(null, "ce client n'existe pas,veullez le verifier");
                } else {

                    gc.insert(commande1);
                    JOptionPane.showMessageDialog(null, "ajout reussi");
                    chargerListe();
                    actualiser();

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauMouseClicked
        // TODO add your handling code here:
        int nbrrow = tableau.getSelectedRow();
        txt_reference.setText(String.valueOf(tableau.getValueAt(nbrrow, 0)));
        nbr_id_client.setText(String.valueOf(tableau.getValueAt(nbrrow, 1)));
        try {

            SimpleDateFormat format = new SimpleDateFormat("yyyy-mm-dd");
            Date daty = format.parse(String.valueOf(tableau.getValueAt(nbrrow, 2)));
            date_commande.setDate(daty);

        } catch (Exception e) {
            e.printStackTrace();

        }
        nbr_quantite.setText(String.valueOf(tableau.getValueAt(nbrrow, 3)));
    }//GEN-LAST:event_tableauMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String txt_condi = txt_reference.getText();

        if (txt_condi.equals("")) {
            JOptionPane.showMessageDialog(null, "veullez selectioner l'element supprimer");
        } else {
            int p = JOptionPane.showConfirmDialog(null, "do you supprimer", "delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                try {

                    gest_commande gc = new gest_commande();
                    gc.delete(txt_condi);
                    JOptionPane.showMessageDialog(null, "suppresion reusii!!");
                    chargerListe();
                    actualiser();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
          String nume=txt_rech.getText();
        
        String titre[] = {"reference_produit", "id_client", "date", "quantite"};
        Object save[][] = new Object[1][1];
        
        try {
            gest_commande gc=new gest_commande();
                 
            int nbr = gc.countSave();
            save = new Object[nbr][titre.length];

            ResultSet res=gc.getByRef(nume);
            int i=0;
            while(res.next()){
                save[i][0] = (Object) res.getString("reference_produit");
                save[i][1] = (Object) res.getString("id_client");
                save[i][2] = (Object) res.getString("date");
                save[i][3] = (Object) res.getString("quantite");
               

                i++;
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        tableau.setModel(new DefaultTableModel(save, titre));
        jScrollPane1.setViewportView(tableau);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_commande;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nbr_id_client;
    private javax.swing.JTextField nbr_quantite;
    private javax.swing.JTable tableau;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_reference;
    // End of variables declaration//GEN-END:variables
}
