/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nyFormulaire;

import java.awt.Color;

/**
 *
 * @author TSIAHY DONILLY
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        lettreC.setVisible(false);
        lettreE.setVisible(false);
        lettreM.setVisible(false);
        lettreO.setVisible(false);
        lettreP.setVisible(false);
        lettreR.setVisible(false);
        lettreR2.setVisible(false);
        lettreS.setVisible(false);
        lettreT.setVisible(false);
        lettreT2.setVisible(false);
        lettreU.setVisible(false);
        lettreU2.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lettreC = new javax.swing.JLabel();
        lettreU = new javax.swing.JLabel();
        lettreM = new javax.swing.JLabel();
        lettreP = new javax.swing.JLabel();
        lettreT = new javax.swing.JLabel();
        lettreU2 = new javax.swing.JLabel();
        lettreR = new javax.swing.JLabel();
        lettreS = new javax.swing.JLabel();
        lettreT2 = new javax.swing.JLabel();
        lettreR2 = new javax.swing.JLabel();
        lettreO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lettreE = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/MENU.png"))); // NOI18N
        jLabel1.setText("click");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 21, 78, -1));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jPanel7.setBackground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1138, 1138, 1138)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 107, -1, 10));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(210, 656));
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lettreC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreC.setText("C");
        jPanel10.add(lettreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 58, 22));

        lettreU.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreU.setText("U");
        jPanel10.add(lettreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 58, 22));

        lettreM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreM.setText("M");
        jPanel10.add(lettreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 58, 22));

        lettreP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreP.setText("P");
        jPanel10.add(lettreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 58, 22));

        lettreT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreT.setText("T");
        jPanel10.add(lettreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 58, 22));

        lettreU2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreU2.setText("U");
        jPanel10.add(lettreU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 60, 30));

        lettreR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreR.setText("R");
        jPanel10.add(lettreR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 58, 22));

        lettreS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreS.setText("S");
        jPanel10.add(lettreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 58, 22));

        lettreT2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreT2.setText("T");
        jPanel10.add(lettreT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 58, 22));

        lettreR2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreR2.setText("R");
        jPanel10.add(lettreR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 58, 22));

        lettreO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreO.setText("O");
        jPanel10.add(lettreO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 58, 22));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 656));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CLIENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ACCUEIL");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("PRODUIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("ACHAT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("COMMANDE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("STOCK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 800));

        jPanel11.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 10, 800));

        jPanel12.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 210, 10));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nyFormulaire/cumputer stor.png"))); // NOI18N
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 70));

        lettreE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lettreE.setText("E");
        jPanel10.add(lettreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 60, 22));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 856));

        combox.setBackground(new java.awt.Color(204, 0, 0));
        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "defaut", "blue", "vert", "orange" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        jPanel1.add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 70, 30));

        jLabel8.setText("change theme");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 90, 20));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1059, 656));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int x=210;
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(x==210){
            jPanel2.setSize(210, 656);
            
        lettreC.setVisible(true);
        lettreE.setVisible(true);
        lettreM.setVisible(true);
        lettreO.setVisible(true);
        lettreP.setVisible(true);
        lettreR.setVisible(true);
        lettreR2.setVisible(true);
        lettreS.setVisible(true);
        lettreT.setVisible(true);
        lettreT2.setVisible(true);
        lettreU.setVisible(true);
        lettreU2.setVisible(true);
            
            Thread th =new Thread(){
                @Override
                public void run(){
                    try {
                        for( int i=210;i>=0;i--){
                        Thread.sleep(1);
                        jPanel2.setSize(i,656);
                       
                        if(i==10){
                            break;
                        }
                    }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            };th.start();
            x=0;
            
        }
        else{
            jPanel2.show();
             jPanel2.setSize(210, 656);
             
        lettreC.setVisible(false);
        lettreE.setVisible(false);
        lettreM.setVisible(false);
        lettreO.setVisible(false);
        lettreP.setVisible(false);
        lettreR.setVisible(false);
        lettreR2.setVisible(false);
        lettreS.setVisible(false);
        lettreT.setVisible(false);
        lettreT2.setVisible(false);
        lettreU.setVisible(false);
        lettreU2.setVisible(false);
           
            Thread th =new Thread(){
                @Override
                public void run(){
                    try {
                        for( int i=0;i<=210;i++){
                        Thread.sleep(1);
                        jPanel2.setSize(i,656);
                        
                    }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            };th.start();
            x=210;
            
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
        String vc=combox.getSelectedItem().toString();
        if(vc.equals("blue")){
            jPanel2.setBackground(Color.blue);
            jPanel3.setBackground(Color.blue);
            jPanel12.setBackground(Color.blue);
            jPanel11.setBackground(Color.blue);
            combox.setBackground(Color.blue);
        }else if(vc.equals("vert")){
            
            jPanel2.setBackground(Color.green);
            jPanel3.setBackground(Color.green);
            
            jPanel12.setBackground(Color.green);
            jPanel11.setBackground(Color.green);
             combox.setBackground(Color.green);
            
        }else if(vc.equals("defaut") ) {
            
            jPanel2.setBackground(Color.red);
            jPanel3.setBackground(Color.red);
            
            jPanel12.setBackground(Color.red);
            jPanel11.setBackground(Color.red);
             combox.setBackground(Color.red);
            
        }
        else{
            jPanel2.setBackground(Color.orange);
            jPanel3.setBackground(Color.orange);
            
            jPanel12.setBackground(Color.orange);
            jPanel11.setBackground(Color.orange);
             combox.setBackground(Color.orange);
            
        }
    }//GEN-LAST:event_comboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cude_client c_cli=new cude_client();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(c_cli).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        crude_achat c_a=new crude_achat();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(c_a).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        crude_produit c_p=new crude_produit();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(c_p).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        crude_commande c_com=new  crude_commande();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(c_com).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lettreC;
    private javax.swing.JLabel lettreE;
    private javax.swing.JLabel lettreM;
    private javax.swing.JLabel lettreO;
    private javax.swing.JLabel lettreP;
    private javax.swing.JLabel lettreR;
    private javax.swing.JLabel lettreR2;
    private javax.swing.JLabel lettreS;
    private javax.swing.JLabel lettreT;
    private javax.swing.JLabel lettreT2;
    private javax.swing.JLabel lettreU;
    private javax.swing.JLabel lettreU2;
    // End of variables declaration//GEN-END:variables
}
